package co.istad.elearning.features.course;

import co.istad.elearning.features.category.Category;
import co.istad.elearning.features.category.CategoryRepository;
import co.istad.elearning.features.course.dto.CourseResponse;
import co.istad.elearning.features.course.dto.CreateCourseRequest;
import co.istad.elearning.features.instructor.InstructorProfile;
import co.istad.elearning.security.AuthUtils;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.http.HttpStatus;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import java.time.LocalDateTime;
import java.util.List;

@Service
public class CourseServiceImpl implements CourseService {

    private final CategoryRepository categoryRepository;
    private final CourseRepository courseRepository;
    private final CourseMapper courseMapper;

    public CourseServiceImpl(CategoryRepository categoryRepository, CourseRepository courseRepository, CourseMapper courseMapper) {
        this.categoryRepository = categoryRepository;
        this.courseRepository = courseRepository;
        this.courseMapper = courseMapper;
    }

//    @Override
//    public CourseResponse createCourse(CreateCourseRequest createCourseRequest, Jwt jwt) {
//
//        if (courseRepository.existsBySlug(createCourseRequest.slug())) {
//            throw new ResponseStatusException(HttpStatus.CONFLICT,
//                    "Slug has already been used");
//        }
//
//        Category category = categoryRepository.findById(createCourseRequest.categoryId())
//                .orElseThrow(() -> new ResponseStatusException(
//                        HttpStatus.NOT_FOUND,
//                        "Category has not found..!"
//                ));
//
//        Course course = courseMapper.mapCreateCourseRequestToCourse(createCourseRequest);
//
//        course.setCategory(category);
//        course.setCountRating(0);
//        course.setStarRating(0F);
//        course.setIsDeleted(false);
//        course.setIsPublished(false);
//
//        course.setInstructorProfile(new InstructorProfile(jwt.getSubject()));
//
//        course = courseRepository.save(course);
//
//        return courseMapper.mapCourseToCourseResponse(course);
//    }

    @Override
    public CourseResponse createCourse(CreateCourseRequest createCourseRequest, Jwt jwt) {
        // TODO: write your logic
        // Validate slug
        if (courseRepository.existsBySlug(createCourseRequest.slug())) {
            throw new ResponseStatusException(HttpStatus.CONFLICT,
                    "Slug has already been used");
        }

        // Validate category
        Category category = categoryRepository.findById(createCourseRequest.categoryId())
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,
                        "Category has not been found"));

        // Transfer data from DTO to Domain Model
        Course course = courseMapper
                .mapCreateCourseRequestToCourse(createCourseRequest);

        // System data (generated by system)
        course.setCategory(category);
        course.setCountRating(0);
        course.setStarRating(0F);
        course.setIsDeleted(false);
        course.setIsPublished(false);

        course.setInstructorProfile(new InstructorProfile(AuthUtils.extractUserId()));

        course = courseRepository.save(course);

        return courseMapper.mapCourseToCourseResponse(course);
    }

    @Override
    public Page<CourseResponse> getAllCourse(int pageNumber, int pageSize) {
        PageRequest pageRequest = PageRequest.of(pageNumber, pageSize);

        return courseRepository.findAll(pageRequest)
                .map(courseMapper::mapCourseToCourseResponse);
    }

    @Override
    public CourseResponse updateById(Integer id, CreateCourseRequest request) {
        return null;
    }
}
