
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://127.0.0.1:8080/realms/a01-m1"
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/db-elearning-a01-m1
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: fdsa
  application:
    name: elearning-a01-m1

server:
  port: 8081
